services:
  # Service for the mysql database
  db:
    image: mysql:latest
    restart: unless-stopped
    container_name: mysql-container-for-car-api
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DATABASE_PASSWORD
      - MYSQL_DATABASE=$DATABASE_NAME
    healthcheck: # To ensure that the flask api is run once the database is ready. Otherwise, there'll be an error.
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    ports:
      - "3306:3306"
    volumes:
      - db_volume:/data/db  # to persist the data
    networks:
      - car-api-network

  # Service for the flask api
  api:
    image: weleassane/car-api-image:v1.0.0

    restart: unless-stopped
    container_name: car-api-container
    env_file: ./.env
    environment:
     - DATABASE_HOST=$DATABASE_HOST
     - DATABASE_USER=$DATABASE_USER
     - DATABASE_PASSWORD=$DATABASE_PASSWORD
     - DATABASE_NAME=$DATABASE_NAME
     - DATABASE_PORT=$DATABASE_PORT

    ports:
      - "5000:5000"
    depends_on:
       db:
          condition: service_healthy # In order to avoid error by waiting the db to be ready
    networks:
      - car-api-network

networks:
  car-api-network:
    driver: bridge

volumes:
  db_volume: