apiVersion: v1
kind: Service
metadata:
  name: car-api
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30000  # Port entre 30000 et 30080
  selector:
    app: car-api
