apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: car-api
  template:
    metadata:
      labels:
        app: car-api
    spec:
      initContainers:
      - name: init-db
        image: busybox
        command: ['sh', '-c', 'until nc -z db 3306; do echo waiting for db; sleep 2; done;']
      containers:
      - name: car-api
        image: weleassane/car-api-image:v1.0.0
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_HOST
          value: "db"
        - name: DATABASE_USER
          value: "root"
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: DATABASE_NAME
          value: "cars_db"
        - name: DATABASE_PORT
          value: "3306"
        readinessProbe:
          httpGet:
            path: /car-api/health/ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /car-api/health/live
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
